<a href="https://colab.research.google.com/github/0xawasthi/ML-learning/blob/main/pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS

Data Preprocessing in Machine Learning using Pandas.

- Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

🎯 Pandas is an open source Python package that is most widely used for data science/data analysis and machine learning tasks. It is built on top of another package named Numpy, which provides support for multi-dimensional arrays. Preprocessing is the process of doing a pre-analysis of data, in order to transform them into a standard and normalized format.

Preprocessing involves the following aspects:
- Missing values
- Data standardization
- Data normalization
- Data binning

In [ ]:
import pandas as pd

In [ ]:
#@ Check pandas version

print(pd.__version__)

2.2.3

## Series in Pandas

It is a one-dimensional array holding data of any type.

In [ ]:
import pandas as pd

a = [1, 2, 3, 4]
myvar = pd.Series(a)

print(myvar)

0    1
1    2
2    3
3    4
dtype: int64

**Labels**

If nothing else is specified, the values are labeled with their index number.

In above example- 0, 1, 2, 3 are labels.

In [ ]:
#@ Create your own label using index

import pandas as pd

a = [2, 3, 5]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

x    2
y    3
z    5
dtype: int64

In [ ]:
print(myvar["x"])

2

In [ ]:
#@ Key/Value objects as Series
# Key becomes the label

import pandas as pd

marks = {"sub1": 55, "sub2": 65, "sub3": 75}
myvar = pd.Series(marks)
print(myvar)

sub1    55
sub2    65
sub3    75
dtype: int64

## Dataframes in Pandas

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:
import pandas as pd

data = {
    "cars": ['BMW', 'Honda', 'Suzuki', 'BYD'],
    "models": ['2007', '2008', '2008', '2022'],
    "passengers": [5, 6, 4, 8]
}
print(data)

{'cars': ['BMW', 'Honda', 'Suzuki', 'BYD'], 'models': ['2007', '2008', '2008', '2022'], 'passengers': [5, 6, 4, 8]}

In [ ]:
#@ Convert this dictionary to DataFrame

df = pd.DataFrame(data)
print(df)

     cars models  passengers
0     BMW   2007           5
1   Honda   2008           6
2  Suzuki   2008           4
3     BYD   2022           8

In [ ]:
df_to_csv = df.to_csv("cars.csv")

In [ ]:
df = pd.read_csv("cars.csv")
df

   Unnamed: 0    cars  models  passengers
0           0     BMW    2007           5
1           1   Honda    2008           6
2           2  Suzuki    2008           4
3           3     BYD    2022           8

In [ ]:
# Locate rows using loc function

print(df.loc[1])

Unnamed: 0        1
cars          Honda
models         2008
passengers        6
Name: 1, dtype: object

In [ ]:
# Return 0 and 1

print(df.loc[[0, 1]])

   Unnamed: 0   cars  models  passengers
0           0    BMW    2007           5
1           1  Honda    2008           6

In [ ]:
# indexing DataFrames

import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

## Data Cleaning with Pandas

Bad data can be:

- Empty cells
- Data in wrong format
- Wrong data
- Duplicates

In [18]:
import pandas as pd

df = pd.read_csv("pandas_dataset.csv")
df

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127     300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
18        45  2020/12/18'     90       112       NaN
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
22        45          NaN    100       119     282.0
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60   12/26/2020    100       120     250.0
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [19]:
df.head(10)

   Duration         Date  Pulse  Maxpulse  Calories
0        60  2020/12/01'    110       130     409.1
1        60  2020/12/02'    117       145     479.0
2        60  2020/12/03'    103       135     340.0
3        45  2020/12/04'    109       175     282.4
4        45  2020/12/05'    117       148     406.0
5        60  2020/12/06'    102       127     300.0
6        60  2020/12/07'    110       136     374.0
7       450  2020/12/08'    104       134     253.3
8        30  2020/12/09'    109       133     195.1
9        60  2020/12/10'     98       124     269.0

In [21]:
print(df.tail(5))

    Duration         Date  Pulse  Maxpulse  Calories
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

Problems in our dataset:

- Data set contains some empty cells ("Date" in row 22 and calories in row 18 and 28)
- The data set contains worng format ("date in row 26)
- The data set contains wrong data ("duratoin in row7)
- The data set contains duplicates (row 11 and 12)

In [ ]:
# To return datasets with no empty cells use dropna()
# df.dropna() will remove empty cells but will not change the dataframe, if we want data frame to be changed, use inplace=true

import pandas as pd