<a href="https://colab.research.google.com/github/0xawasthi/ML-learning/blob/main/pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS

Data Preprocessing in Machine Learning using Pandas.

- Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

🎯 Pandas is an open source Python package that is most widely used for data science/data analysis and machine learning tasks. It is built on top of another package named Numpy, which provides support for multi-dimensional arrays. Preprocessing is the process of doing a pre-analysis of data, in order to transform them into a standard and normalized format.

Preprocessing involves the following aspects:
- Missing values
- Data standardization
- Data normalization
- Data binning

In [58]:
import pandas as pd

In [59]:
#@ Check pandas version

print(pd.__version__)

2.2.3

## Series in Pandas

It is a one-dimensional array holding data of any type.

In [60]:
import pandas as pd

a = [1, 2, 3, 4]
myvar = pd.Series(a)

print(myvar)

0    1
1    2
2    3
3    4
dtype: int64

**Labels**

If nothing else is specified, the values are labeled with their index number.

In above example- 0, 1, 2, 3 are labels.

In [61]:
#@ Create your own label using index

import pandas as pd

a = [2, 3, 5]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

x    2
y    3
z    5
dtype: int64

In [62]:
print(myvar["x"])

2

In [63]:
#@ Key/Value objects as Series
# Key becomes the label

import pandas as pd

marks = {"sub1": 55, "sub2": 65, "sub3": 75}
myvar = pd.Series(marks)
print(myvar)

sub1    55
sub2    65
sub3    75
dtype: int64

## Dataframes in Pandas

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [64]:
import pandas as pd

data = {
    "cars": ['BMW', 'Honda', 'Suzuki', 'BYD'],
    "models": ['2007', '2008', '2008', '2022'],
    "passengers": [5, 6, 4, 8]
}
print(data)

{'cars': ['BMW', 'Honda', 'Suzuki', 'BYD'], 'models': ['2007', '2008', '2008', '2022'], 'passengers': [5, 6, 4, 8]}

In [65]:
#@ Convert this dictionary to DataFrame

df = pd.DataFrame(data)
print(df)

     cars models  passengers
0     BMW   2007           5
1   Honda   2008           6
2  Suzuki   2008           4
3     BYD   2022           8

In [66]:
df_to_csv = df.to_csv("cars.csv")

In [67]:
df = pd.read_csv("cars.csv")
df

   Unnamed: 0    cars  models  passengers
0           0     BMW    2007           5
1           1   Honda    2008           6
2           2  Suzuki    2008           4
3           3     BYD    2022           8

In [68]:
# Locate rows using loc function

print(df.loc[1])

Unnamed: 0        1
cars          Honda
models         2008
passengers        6
Name: 1, dtype: object

In [69]:
# Return 0 and 1

print(df.loc[[0, 1]])

   Unnamed: 0   cars  models  passengers
0           0    BMW    2007           5
1           1  Honda    2008           6

In [70]:
# indexing DataFrames

import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [71]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

## Data Cleaning with Pandas

Bad data can be:

- Empty cells
- Data in wrong format
- Wrong data
- Duplicates

In [72]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_datasets/pandas_dataset.csv")
df

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127     300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
18        45  2020/12/18'     90       112       NaN
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
22        45          NaN    100       119     282.0
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60   12/26/2020    100       120     250.0
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [73]:
df.head(10)

   Duration         Date  Pulse  Maxpulse  Calories
0        60  2020/12/01'    110       130     409.1
1        60  2020/12/02'    117       145     479.0
2        60  2020/12/03'    103       135     340.0
3        45  2020/12/04'    109       175     282.4
4        45  2020/12/05'    117       148     406.0
5        60  2020/12/06'    102       127     300.0
6        60  2020/12/07'    110       136     374.0
7       450  2020/12/08'    104       134     253.3
8        30  2020/12/09'    109       133     195.1
9        60  2020/12/10'     98       124     269.0

In [74]:
print(df.tail(5))

    Duration         Date  Pulse  Maxpulse  Calories
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

Problems in our dataset:

- Data set contains some empty cells ("Date" in row 22 and calories in row 18 and 28)
- The data set contains worng format ("date in row 26)
- The data set contains wrong data ("duratoin in row7)
- The data set contains duplicates (row 11 and 12)

In [75]:
# To return datasets with no empty cells use dropna()
# df.dropna() will remove empty cells but will not change the dataframe, if we want data frame to be changed, use inplace=true

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_datasets/pandas_dataset.csv")
new_df = df.dropna()
print(new_df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127     300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60   12/26/2020    100       120     250.0
27        60  2020/12/27'     92       118     241.0
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [76]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_datasets/pandas_dataset.csv")
df.dropna(inplace = True)
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127     300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60   12/26/2020    100       120     250.0
27        60  2020/12/27'     92       118     241.0
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

## Pandas Exercise 1

In [77]:
import pandas as pd
import numpy as np

In [78]:
#@ Loading the dataset

df = pd.read_csv("/content/drive/MyDrive/ML_datasets/en.openfoodfacts.org.products.tsv", sep='\t')

/tmp/ipykernel_3273/879971820.py:3: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/ML_datasets/en.openfoodfacts.org.products.tsv", sep='\t')

In [79]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
#@ What is the total number of data that I am working with?
#@ Know your data first...

df.shape

(356027, 163)

In [81]:
df.shape[0] # Returns only number of rows

356027

In [82]:
df.shape[1] # Returns only number of columns

163

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB

In [84]:
#@ print only columns

df.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

In [85]:
#@ What is the name of the column at 105 position?
df.columns[104]

'-glucose_100g'

In [86]:
df.dtypes['-glucose_100g']

dtype('float64')

In [87]:
#@ Look for data index

df.index

RangeIndex(start=0, stop=356027, step=1)

In [88]:
#@ Which field is at 19th

df.columns[18]

'origins_tags'

In [89]:
#@ What is the product name of 19th observation

df.values[18][7]

'Lotus Organic Brown Jasmine Rice'

## Pandas Exercise 2

In [90]:
import pandas as pd
import numpy as np

In [91]:
# Load dataset

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep='|', index_col='user_id')

In [92]:
df.head(10)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703

In [93]:
#@ How many numbers of data we have

df.shape[0]

943

In [94]:
#@ print all the columns

df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [95]:
#@ What's the data type of each column

df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [96]:
#@ only print occupation column

df.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [97]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [98]:
#@ Let's figure out how many unique occupations are there in dataset

df.occupation.nunique() # returns the count of unique elements

21

In [99]:
df.occupation.value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [100]:
df.occupation.value_counts().count()

np.int64(21)

In [101]:
#@ Let's describe your dataset by summarizing it

df.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

Only numeric columns are returned, if you only describe the dataframe.

In [102]:
#@ If we need all then

df.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [103]:
#@ What if I need only occupation

df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [104]:
#@ What is the mean age of the users

round(df.age.mean())

34

In [105]:
#@ the least occurance of age

df.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

## Pandas Exercise 3

In [106]:
import pandas as pd

In [107]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep = '\t')

In [108]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [109]:
#@ Number observation

df.shape[0]

4622

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [111]:
df.shape[1]

5

In [112]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [115]:
#@ Which was the most ordered items
# group by

i = df.groupby('item_name')
i = i.sum()
i = i.sort_values(['quantity'], ascending=False)
i.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [114]:
#@ What was the most ordered item in the choice description column

df.groupby('choice_description').sum().sort_values(['quantity'], ascending=False).head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

In [117]:
import pandas as pd
df = pd.DataFrame({
    "team":   ["A", "A", "B", "B", "C", "C", "A"],
    "player": ["p1", "p2", "p3", "p4", "p5", "p6", "p7"],
    "points": [10, 15, 8, 12, 20, 5, 7],
    "assists":[3, 5, 2, 4, 6, 1, 2],
})
df

  team player  points  assists
0    A     p1      10        3
1    A     p2      15        5
2    B     p3       8        2
3    B     p4      12        4
4    C     p5      20        6
5    C     p6       5        1
6    A     p7       7        2

In [118]:
df.groupby("team")

In [119]:
df.groupby('team')['points'].sum()

team
A    32
B    20
C    25
Name: points, dtype: int64

In [121]:
df.groupby('team')['points'].mean()

team
A    10.666667
B    10.000000
C    12.500000
Name: points, dtype: float64

In [125]:
df.groupby('team')['points'].agg(['mean', 'sum', 'count', 'max', 'min'])

           mean  sum  count  max  min
team
A     10.666667   32      3   15    7
B     10.000000   20      2   12    8
C     12.500000   25      2   20    5

In [128]:
df.groupby('team').size()

team
A    3
B    2
C    2
dtype: int64

In [127]:
df.groupby('team').count()

      player  points  assists
team
A          3       3        3
B          2       2        2
C          2       2        2